// Countries supported across hero-sms, 5sim, and sms-man
// Sorted by most popular first, then alphabetically

const COUNTRIES = [
  { code: 'any',  name: 'Any Country (Cheapest)', flag: '🌍' },
  { code: 'us',   name: 'United States',    flag: '🇺🇸' },
  { code: 'gb',   name: 'United Kingdom',   flag: '🇬🇧' },
  { code: 'ca',   name: 'Canada',           flag: '🇨🇦' },
  { code: 'au',   name: 'Australia',        flag: '🇦🇺' },
  { code: 'ng',   name: 'Nigeria',          flag: '🇳🇬' },
  { code: 'in',   name: 'India',            flag: '🇮🇳' },
  { code: 'id',   name: 'Indonesia',        flag: '🇮🇩' },
  { code: 'ru',   name: 'Russia',           flag: '🇷🇺' },
  { code: 'br',   name: 'Brazil',           flag: '🇧🇷' },
  { code: 'mx',   name: 'Mexico',           flag: '🇲🇽' },
  { code: 'de',   name: 'Germany',          flag: '🇩🇪' },
  { code: 'fr',   name: 'France',           flag: '🇫🇷' },
  { code: 'pl',   name: 'Poland',           flag: '🇵🇱' },
  { code: 'ua',   name: 'Ukraine',          flag: '🇺🇦' },
  { code: 'ph',   name: 'Philippines',      flag: '🇵🇭' },
  { code: 'vn',   name: 'Vietnam',          flag: '🇻🇳' },
  { code: 'th',   name: 'Thailand',         flag: '🇹🇭' },
  { code: 'bd',   name: 'Bangladesh',       flag: '🇧🇩' },
  { code: 'pk',   name: 'Pakistan',         flag: '🇵🇰' },
  { code: 'eg',   name: 'Egypt',            flag: '🇪🇬' },
  { code: 'ke',   name: 'Kenya',            flag: '🇰🇪' },
  { code: 'gh',   name: 'Ghana',            flag: '🇬🇭' },
  { code: 'za',   name: 'South Africa',     flag: '🇿🇦' },
  { code: 'tz',   name: 'Tanzania',         flag: '🇹🇿' },
  { code: 'et',   name: 'Ethiopia',         flag: '🇪🇹' },
  { code: 'ug',   name: 'Uganda',           flag: '🇺🇬' },
  { code: 'cm',   name: 'Cameroon',         flag: '🇨🇲' },
  { code: 'ci',   name: 'Ivory Coast',      flag: '🇨🇮' },
  { code: 'sn',   name: 'Senegal',          flag: '🇸🇳' },
  { code: 'ma',   name: 'Morocco',          flag: '🇲🇦' },
  { code: 'dz',   name: 'Algeria',          flag: '🇩🇿' },
  { code: 'tn',   name: 'Tunisia',          flag: '🇹🇳' },
  { code: 'ly',   name: 'Libya',            flag: '🇱🇾' },
  { code: 'sd',   name: 'Sudan',            flag: '🇸🇩' },
  { code: 'ao',   name: 'Angola',           flag: '🇦🇴' },
  { code: 'mz',   name: 'Mozambique',       flag: '🇲🇿' },
  { code: 'zw',   name: 'Zimbabwe',         flag: '🇿🇼' },
  { code: 'zm',   name: 'Zambia',           flag: '🇿🇲' },
  { code: 'cd',   name: 'Congo (DRC)',       flag: '🇨🇩' },
  { code: 'cg',   name: 'Congo',            flag: '🇨🇬' },
  { code: 'ml',   name: 'Mali',             flag: '🇲🇱' },
  { code: 'ne',   name: 'Niger',            flag: '🇳🇪' },
  { code: 'bf',   name: 'Burkina Faso',     flag: '🇧🇫' },
  { code: 'tg',   name: 'Togo',             flag: '🇹🇬' },
  { code: 'bj',   name: 'Benin',            flag: '🇧🇯' },
  { code: 'sl',   name: 'Sierra Leone',     flag: '🇸🇱' },
  { code: 'lr',   name: 'Liberia',          flag: '🇱🇷' },
  { code: 'gn',   name: 'Guinea',           flag: '🇬🇳' },
  { code: 'rw',   name: 'Rwanda',           flag: '🇷🇼' },
  { code: 'bi',   name: 'Burundi',          flag: '🇧🇮' },
  { code: 'mw',   name: 'Malawi',           flag: '🇲🇼' },
  { code: 'bw',   name: 'Botswana',         flag: '🇧🇼' },
  { code: 'na',   name: 'Namibia',          flag: '🇳🇦' },
  { code: 'mu',   name: 'Mauritius',        flag: '🇲🇺' },
  { code: 'so',   name: 'Somalia',          flag: '🇸🇴' },
  { code: 'er',   name: 'Eritrea',          flag: '🇪🇷' },
  { code: 'dj',   name: 'Djibouti',         flag: '🇩🇯' },
  { code: 'iq',   name: 'Iraq',             flag: '🇮🇶' },
  { code: 'sa',   name: 'Saudi Arabia',     flag: '🇸🇦' },
  { code: 'ae',   name: 'UAE',              flag: '🇦🇪' },
  { code: 'jo',   name: 'Jordan',           flag: '🇯🇴' },
  { code: 'lb',   name: 'Lebanon',          flag: '🇱🇧' },
  { code: 'sy',   name: 'Syria',            flag: '🇸🇾' },
  { code: 'ye',   name: 'Yemen',            flag: '🇾🇪' },
  { code: 'om',   name: 'Oman',             flag: '🇴🇲' },
  { code: 'kw',   name: 'Kuwait',           flag: '🇰🇼' },
  { code: 'qa',   name: 'Qatar',            flag: '🇶🇦' },
  { code: 'bh',   name: 'Bahrain',          flag: '🇧🇭' },
  { code: 'il',   name: 'Israel',           flag: '🇮🇱' },
  { code: 'tr',   name: 'Turkey',           flag: '🇹🇷' },
  { code: 'ir',   name: 'Iran',             flag: '🇮🇷' },
  { code: 'af',   name: 'Afghanistan',      flag: '🇦🇫' },
  { code: 'cn',   name: 'China',            flag: '🇨🇳' },
  { code: 'jp',   name: 'Japan',            flag: '🇯🇵' },
  { code: 'kr',   name: 'South Korea',      flag: '🇰🇷' },
  { code: 'kp',   name: 'North Korea',      flag: '🇰🇵' },
  { code: 'tw',   name: 'Taiwan',           flag: '🇹🇼' },
  { code: 'hk',   name: 'Hong Kong',        flag: '🇭🇰' },
  { code: 'sg',   name: 'Singapore',        flag: '🇸🇬' },
  { code: 'my',   name: 'Malaysia',         flag: '🇲🇾' },
  { code: 'mm',   name: 'Myanmar',          flag: '🇲🇲' },
  { code: 'kh',   name: 'Cambodia',         flag: '🇰🇭' },
  { code: 'la',   name: 'Laos',             flag: '🇱🇦' },
  { code: 'np',   name: 'Nepal',            flag: '🇳🇵' },
  { code: 'lk',   name: 'Sri Lanka',        flag: '🇱🇰' },
  { code: 'mn',   name: 'Mongolia',         flag: '🇲🇳' },
  { code: 'kz',   name: 'Kazakhstan',       flag: '🇰🇿' },
  { code: 'uz',   name: 'Uzbekistan',       flag: '🇺🇿' },
  { code: 'az',   name: 'Azerbaijan',       flag: '🇦🇿' },
  { code: 'ge',   name: 'Georgia',          flag: '🇬🇪' },
  { code: 'am',   name: 'Armenia',          flag: '🇦🇲' },
  { code: 'tm',   name: 'Turkmenistan',     flag: '🇹🇲' },
  { code: 'kg',   name: 'Kyrgyzstan',       flag: '🇰🇬' },
  { code: 'tj',   name: 'Tajikistan',       flag: '🇹🇯' },
  { code: 'md',   name: 'Moldova',          flag: '🇲🇩' },
  { code: 'by',   name: 'Belarus',          flag: '🇧🇾' },
  { code: 'lt',   name: 'Lithuania',        flag: '🇱🇹' },
  { code: 'lv',   name: 'Latvia',           flag: '🇱🇻' },
  { code: 'ee',   name: 'Estonia',          flag: '🇪🇪' },
  { code: 'fi',   name: 'Finland',          flag: '🇫🇮' },
  { code: 'se',   name: 'Sweden',           flag: '🇸🇪' },
  { code: 'no',   name: 'Norway',           flag: '🇳🇴' },
  { code: 'dk',   name: 'Denmark',          flag: '🇩🇰' },
  { code: 'nl',   name: 'Netherlands',      flag: '🇳🇱' },
  { code: 'be',   name: 'Belgium',          flag: '🇧🇪' },
  { code: 'ch',   name: 'Switzerland',      flag: '🇨🇭' },
  { code: 'at',   name: 'Austria',          flag: '🇦🇹' },
  { code: 'es',   name: 'Spain',            flag: '🇪🇸' },
  { code: 'pt',   name: 'Portugal',         flag: '🇵🇹' },
  { code: 'it',   name: 'Italy',            flag: '🇮🇹' },
  { code: 'gr',   name: 'Greece',           flag: '🇬🇷' },
  { code: 'cz',   name: 'Czech Republic',   flag: '🇨🇿' },
  { code: 'sk',   name: 'Slovakia',         flag: '🇸🇰' },
  { code: 'hu',   name: 'Hungary',          flag: '🇭🇺' },
  { code: 'ro',   name: 'Romania',          flag: '🇷🇴' },
  { code: 'bg',   name: 'Bulgaria',         flag: '🇧🇬' },
  { code: 'rs',   name: 'Serbia',           flag: '🇷🇸' },
  { code: 'hr',   name: 'Croatia',          flag: '🇭🇷' },
  { code: 'ba',   name: 'Bosnia',           flag: '🇧🇦' },
  { code: 'si',   name: 'Slovenia',         flag: '🇸🇮' },
  { code: 'mk',   name: 'North Macedonia',  flag: '🇲🇰' },
  { code: 'al',   name: 'Albania',          flag: '🇦🇱' },
  { code: 'me',   name: 'Montenegro',       flag: '🇲🇪' },
  { code: 'xk',   name: 'Kosovo',           flag: '🇽🇰' },
  { code: 'ie',   name: 'Ireland',          flag: '🇮🇪' },
  { code: 'is',   name: 'Iceland',          flag: '🇮🇸' },
  { code: 'mt',   name: 'Malta',            flag: '🇲🇹' },
  { code: 'cy',   name: 'Cyprus',           flag: '🇨🇾' },
  { code: 'lu',   name: 'Luxembourg',       flag: '🇱🇺' },
  { code: 'ar',   name: 'Argentina',        flag: '🇦🇷' },
  { code: 'cl',   name: 'Chile',            flag: '🇨🇱' },
  { code: 'co',   name: 'Colombia',         flag: '🇨🇴' },
  { code: 'pe',   name: 'Peru',             flag: '🇵🇪' },
  { code: 've',   name: 'Venezuela',        flag: '🇻🇪' },
  { code: 'ec',   name: 'Ecuador',          flag: '🇪🇨' },
  { code: 'bo',   name: 'Bolivia',          flag: '🇧🇴' },
  { code: 'py',   name: 'Paraguay',         flag: '🇵🇾' },
  { code: 'uy',   name: 'Uruguay',          flag: '🇺🇾' },
  { code: 'cr',   name: 'Costa Rica',       flag: '🇨🇷' },
  { code: 'gt',   name: 'Guatemala',        flag: '🇬🇹' },
  { code: 'hn',   name: 'Honduras',         flag: '🇭🇳' },
  { code: 'sv',   name: 'El Salvador',      flag: '🇸🇻' },
  { code: 'ni',   name: 'Nicaragua',        flag: '🇳🇮' },
  { code: 'pa',   name: 'Panama',           flag: '🇵🇦' },
  { code: 'cu',   name: 'Cuba',             flag: '🇨🇺' },
  { code: 'do',   name: 'Dominican Republic', flag: '🇩🇴' },
  { code: 'ht',   name: 'Haiti',            flag: '🇭🇹' },
  { code: 'jm',   name: 'Jamaica',          flag: '🇯🇲' },
  { code: 'tt',   name: 'Trinidad & Tobago', flag: '🇹🇹' },
  { code: 'nz',   name: 'New Zealand',      flag: '🇳🇿' },
  { code: 'fj',   name: 'Fiji',             flag: '🇫🇯' },
  { code: 'pg',   name: 'Papua New Guinea', flag: '🇵🇬' },
];

export default COUNTRIES;

// For easy lookup
export const COUNTRY_MAP = Object.fromEntries(COUNTRIES.map(c => [c.code, c]));
